#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
#  MY-PROJECT — Setup  (macOS / Linux / WSL)
#
#  Template generated by LeafHub. Two lines to customize (marked CUSTOMIZE),
#  then add your project-specific steps at the bottom.
#
#  Usage (after git clone):
#    chmod +x setup.sh && ./setup.sh
#
#  Options:
#    --reinstall      Delete and recreate the .venv
#    --headless       Non-interactive / CI mode; skips all prompts
#    --doctor         Run environment check only, then exit
#    --from-installer Internal flag set by install.sh (adjusts banner only)
# ──────────────────────────────────────────────────────────────────────────────

# ── CUSTOMIZE ─────────────────────────────────────────────────────────────────
PROJECT_NAME="my-project"    # leafhub project name (lowercase slug, matches repo name)
LEAFHUB_ALIAS="default"      # must match hub.get_key("<alias>") in runtime code
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
REQUIREMENTS="$SCRIPT_DIR/requirements.txt"
BIN_DIR="$HOME/.local/bin"
PROJECT_BIN="$VENV_DIR/bin/$PROJECT_NAME"
PROJECT_LINK="$BIN_DIR/$PROJECT_NAME"
ORIGINAL_PATH="${PATH:-}"
PATH_PERSISTED=0

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 && -z "${NO_COLOR:-}" && "${TERM:-dumb}" != "dumb" ]]; then
    BOLD='\033[1m'; GREEN='\033[38;2;0;229;180m'; YELLOW='\033[38;2;255;176;32m'
    RED='\033[38;2;230;57;70m'; MUTED='\033[38;2;110;120;148m'; NC='\033[0m'
else
    BOLD='' GREEN='' YELLOW='' RED='' MUTED='' NC=''
fi

ok()      { echo -e "${GREEN}✓${NC}  $*"; }
info()    { echo -e "${MUTED}·${NC}  $*"; }
warn()    { echo -e "${YELLOW}!${NC}  $*"; }
fail()    { echo -e "${RED}✗${NC}  $*" >&2; exit 1; }
section() { echo ""; echo -e "${BOLD}── $* ──${NC}"; }

# ── Argument parsing ──────────────────────────────────────────────────────────
REINSTALL=false
HEADLESS=false
DOCTOR=false
FROM_INSTALLER=false

for arg in "$@"; do
    case "$arg" in
        --reinstall)       REINSTALL=true ;;
        --headless)        HEADLESS=true ;;
        --doctor)          DOCTOR=true ;;
        --from-installer)  FROM_INSTALLER=true ;;
        --help|-h)
            echo "Usage: ./setup.sh [--reinstall] [--headless] [--doctor]"
            exit 0
            ;;
        *) warn "Unknown option: $arg  (ignored)" ;;
    esac
done

# ── Helpers ───────────────────────────────────────────────────────────────────

path_has_dir() {
    case ":${1}:" in *":${2%/}:"*) return 0 ;; *) return 1 ;; esac
}

detect_rc_file() {
    local shell_name
    shell_name="$(basename "${SHELL:-bash}")"
    case "$shell_name" in
        zsh)  echo "$HOME/.zshrc" ;;
        bash)
            if [[ "${OS:-}" == "macos" ]]; then echo "$HOME/.bash_profile"
            elif [[ -f "$HOME/.bashrc" ]]; then echo "$HOME/.bashrc"
            else echo "$HOME/.bash_profile"
            fi ;;
        *)
            if [[ -f "$HOME/.bashrc" ]]; then echo "$HOME/.bashrc"
            else echo "$HOME/.bash_profile"
            fi ;;
    esac
}

ensure_local_bin_on_path() {
    mkdir -p "$BIN_DIR"
    export PATH="$BIN_DIR:$PATH"
    hash -r 2>/dev/null || true

    local marker="# Added by $PROJECT_NAME installer"
    local line='export PATH="$HOME/.local/bin:$PATH"'
    local target rc
    target="$(detect_rc_file)"

    for rc in "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshrc" "$HOME/.profile"; do
        if [[ -f "$rc" ]] && grep -qF '.local/bin' "$rc" 2>/dev/null; then
            PATH_PERSISTED=1; return 0
        fi
    done

    if [[ ! -f "$target" ]] && ! touch "$target" 2>/dev/null; then
        warn "Could not create $(basename "$target") for CLI registration."; return 0
    fi
    if [[ ! -w "$target" ]]; then
        warn "Could not update $(basename "$target") for CLI registration."; return 0
    fi
    if printf '\n%s\n%s\n' "$marker" "$line" >> "$target"; then
        info "Added ~/.local/bin to PATH in $(basename "$target")"
        PATH_PERSISTED=1
    else
        warn "Could not update $(basename "$target") for CLI registration."
    fi
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
if [[ "$FROM_INSTALLER" == "true" ]]; then
    echo -e "${BOLD}  $PROJECT_NAME — Installing${NC}"
else
    echo -e "${BOLD}  $PROJECT_NAME — Setup${NC}"
fi
echo -e "${MUTED}  Project dir: $SCRIPT_DIR${NC}"
echo ""

# ── Step 1 / 5 — Platform ─────────────────────────────────────────────────────
section "Step 1 / 5  —  Platform"

OS="unknown"
if   [[ "$OSTYPE" == "darwin"* ]];                                    then OS="macos"
elif [[ -n "${WSL_DISTRO_NAME:-}" || -n "${WSL_INTEROP:-}" ]];        then OS="wsl"
elif [[ "$OSTYPE" == "linux-gnu"* || "$OSTYPE" == "linux"* ]];        then OS="linux"
fi
[[ "$OS" == "unknown" ]] && \
    fail "Unsupported operating system ($OSTYPE).\n  On Windows run: install.ps1"
ok "Platform: $OS"

# ── Step 2 / 5 — Python ───────────────────────────────────────────────────────
section "Step 2 / 5  —  Python"

PYTHON=""
find_python() {
    local ver maj min
    for cmd in python3.13 python3.12 python3.11 python3.10 python3 python; do
        command -v "$cmd" >/dev/null 2>&1 || continue
        ver="$("$cmd" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || true)"
        [[ -z "$ver" ]] && continue
        maj="${ver%%.*}"; min="${ver##*.}"
        [[ "$maj" -ge 3 && "$min" -ge 10 ]] && echo "$cmd" && return 0
    done
    return 1
}

if ! PYTHON="$(find_python)"; then
    fail "Python 3.10+ is required but was not found.\n  macOS: brew install python@3.12\n  Ubuntu: sudo apt install python3.12 python3.12-venv"
fi
ok "Python: $PYTHON ($("$PYTHON" -c 'import sys; print(sys.version.split()[0])'))"

# ── Step 3 / 5 — Virtual environment ─────────────────────────────────────────
section "Step 3 / 5  —  Virtual environment"

VENV_PYTHON="$VENV_DIR/bin/python"
VENV_PIP="$VENV_DIR/bin/pip"

if [[ -d "$VENV_DIR" ]]; then
    if [[ "$REINSTALL" == "true" ]]; then
        info "Removing existing .venv (--reinstall) ..."
        rm -rf "$VENV_DIR"
    elif [[ ! -x "$VENV_PYTHON" ]]; then
        warn "Existing .venv appears broken — recreating ..."
        rm -rf "$VENV_DIR"
    elif ! "$VENV_PIP" --version >/dev/null 2>&1; then
        warn "Existing .venv has stale paths (project directory was moved) — recreating ..."
        rm -rf "$VENV_DIR"
    else
        ok ".venv exists — reusing  (--reinstall to force rebuild)"
    fi
fi

if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating .venv with $PYTHON ..."
    "$PYTHON" -m venv "$VENV_DIR"
    ok ".venv created."
fi

info "Upgrading pip ..."
"$VENV_PYTHON" -m pip install --upgrade pip --quiet

# CUSTOMIZE: adjust pip install commands for your project
if [[ "$OS" != "macos" ]] && ! command -v nvidia-smi >/dev/null 2>&1; then
    info "No CUDA detected — installing CPU-only torch ..."
    "$VENV_PIP" install "torch>=2.4.0" \
        --index-url https://download.pytorch.org/whl/cpu --quiet
fi

info "Installing dependencies ..."
[[ -f "$REQUIREMENTS" ]] && "$VENV_PIP" install -r "$REQUIREMENTS" --quiet
"$VENV_PIP" install -e "$SCRIPT_DIR[leafhub]" --quiet
ok "Dependencies installed."

# ── Step 4 / 5 — CLI registration ────────────────────────────────────────────
section "Step 4 / 5  —  CLI registration"

if [[ ! -x "$PROJECT_BIN" ]]; then
    fail "Entry point not found after install: $PROJECT_BIN\n  Check [project.scripts] in pyproject.toml."
fi

if [[ "$DOCTOR" == "true" ]]; then
    # CUSTOMIZE: replace with your project's doctor/check command
    info "--doctor: run your environment check here, then exit"
    exit 0
fi

if [[ -L "$PROJECT_LINK" ]]; then
    existing_target="$(readlink -f "$PROJECT_LINK" 2>/dev/null || true)"
    if [[ "$existing_target" == "$PROJECT_BIN" ]]; then
        ok "CLI already registered: $PROJECT_LINK"
        path_has_dir "$ORIGINAL_PATH" "$BIN_DIR" && PATH_PERSISTED=1 || ensure_local_bin_on_path
    else
        ensure_local_bin_on_path
        ln -sf "$PROJECT_BIN" "$PROJECT_LINK"
        ok "Updated CLI link: $PROJECT_NAME → $PROJECT_BIN"
    fi
else
    ensure_local_bin_on_path
    ln -sf "$PROJECT_BIN" "$PROJECT_LINK"
    ok "Registered: $PROJECT_LINK"
fi

if ! path_has_dir "$ORIGINAL_PATH" "$BIN_DIR"; then
    if [[ "$PATH_PERSISTED" -eq 1 ]]; then
        warn "$BIN_DIR not yet in your current shell's PATH."
        warn "Open a new terminal, or run:  export PATH=\"\$HOME/.local/bin:\$PATH\""
    else
        warn "Could not update your shell RC file."
        warn "Add to your shell config:  export PATH=\"\$HOME/.local/bin:\$PATH\""
    fi
fi

# ── Step 5 / 5 — LeafHub ─────────────────────────────────────────────────────
section "Step 5 / 5  —  LeafHub"

# Load register.sh — provides leafhub_setup_project().
# Resolution order:
#   1. leafhub shell-helper     — system PATH binary (fast, offline)
#   2. leafhub_dist/register.sh — local distributed copy (offline fallback)
#   3. GitHub curl              — first-time bootstrap, network required
_lh_content=""
if _lh_content="$(leafhub shell-helper 2>/dev/null)" && [[ -n "$_lh_content" ]]; then
    eval "$_lh_content"
elif [[ -x "$VENV_DIR/bin/leafhub" ]] \
    && _lh_content="$("$VENV_DIR/bin/leafhub" shell-helper 2>/dev/null)" \
    && [[ -n "$_lh_content" ]]; then
    eval "$_lh_content"
elif [[ -f "$SCRIPT_DIR/leafhub_dist/register.sh" ]]; then
    # shellcheck disable=SC1091
    source "$SCRIPT_DIR/leafhub_dist/register.sh"
else
    info "Fetching LeafHub installer ..."
    _TMP_REG="$(mktemp)"
    if ! curl -fsSL \
            https://raw.githubusercontent.com/Rebas9512/Leafhub/main/register.sh \
            -o "$_TMP_REG" 2>/dev/null; then
        rm -f "$_TMP_REG"
        fail "Could not fetch LeafHub installer.\n  Install manually: https://github.com/Rebas9512/Leafhub\n  Then re-run: ./setup.sh"
    fi
    # shellcheck disable=SC1090
    source "$_TMP_REG"
    rm -f "$_TMP_REG"
fi
unset _lh_content

[[ "$HEADLESS" == "true" ]] && export LEAFHUB_HEADLESS=1

leafhub_setup_project "$PROJECT_NAME" "$SCRIPT_DIR" "$LEAFHUB_ALIAS" \
    || fail "LeafHub registration failed.\n  Install LeafHub and retry: https://github.com/Rebas9512/Leafhub"

ok "LeafHub integration complete."

# ── CUSTOMIZE: project-specific steps ────────────────────────────────────────
# Add steps here: model downloads, database setup, config generation, etc.
# Example:
#   section "Step 6 / 6  —  Download models"
#   "$PROJECT_BIN" setup
# ─────────────────────────────────────────────────────────────────────────────

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}  Setup complete!${NC}"
echo ""
if path_has_dir "$ORIGINAL_PATH" "$BIN_DIR"; then
    echo -e "  ${GREEN}$PROJECT_NAME run${NC}"
elif [[ "$PATH_PERSISTED" -eq 1 ]]; then
    echo "  Open a new terminal, then:"
    echo -e "    ${GREEN}$PROJECT_NAME run${NC}"
else
    echo "  Add ~/.local/bin to PATH, then:"
    echo -e "    ${GREEN}export PATH=\"\$HOME/.local/bin:\$PATH\"${NC}"
    echo -e "    ${GREEN}$PROJECT_NAME run${NC}"
fi
echo ""
