"""
Pipeline orchestration.

Execution order:
  Step 0  — Resolve model client from Leafhub
  Step 0b — Probe model capabilities (1x1 PNG test request)
  Step 1  — Scrape: Playwright navigates, collects network + screenshot
  Step 2  — Extract: JS runs in browser, returns CSS/font/animation data
             (steps 1+2 are integrated inside scraper.scrape())
  Step 3  — Aggregate: merge network entries + extractor output
  Step 4  — Report: call LLM with structured data (+screenshot if vision)
"""
from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from .aggregator import aggregate
from .model      import Cap, ResolvedModel, probe_caps, resolve
from .pdf        import md_to_pdf
from .reporter   import generate_report
from .scraper    import scrape

_PROMPTS_DIR = Path(__file__).parent.parent / "prompts"
_OUTPUTS_DIR = Path(__file__).parent.parent / "outputs"


def run(url: str, alias: str = "llm", *, pdf: bool = True) -> Path:
    """
    Full pipeline: URL in, report.md out.
    Returns the path to the generated report file.
    """
    output_dir = _make_output_dir(url)
    t_start    = time.monotonic()

    # ── Step 0: model resolution + capability probe ───────────────────────────
    print(f"[leafscan] Connecting to model (alias={alias!r}) ...", flush=True)
    model = resolve(alias=alias)

    print(f"[leafscan] Probing capabilities ({model.model}) ...", flush=True)
    caps      = probe_caps(model)
    model.caps = caps
    cap_label  = "vision + text" if Cap.VISION in caps else "text-only"
    print(f"[leafscan] Capability confirmed: {cap_label}", flush=True)

    # ── Steps 1+2: scrape + extract ───────────────────────────────────────────
    print(f"[leafscan] Scraping {url} ...", flush=True)
    result = scrape(url, output_dir)
    print(f"[leafscan] Captured {len(result.screenshot_paths)} scroll frames", flush=True)

    # Persist raw intermediate data for debugging
    _write_json(output_dir / "css.json",    result.css_data)
    _write_json(output_dir / "network.json", result.network_entries)

    # ── Step 3: aggregate ─────────────────────────────────────────────────────
    print("[leafscan] Aggregating ...", flush=True)
    assets_data = aggregate(result.css_data, result.network_entries)
    _write_json(output_dir / "assets.json", assets_data)

    # ── Step 4: LLM report ────────────────────────────────────────────────────
    print("[leafscan] Generating report ...", flush=True)
    system_prompt = (_PROMPTS_DIR / "design_report.txt").read_text()
    report_md     = generate_report(
        css_data         = result.css_data,
        assets_data      = assets_data,
        screenshot_paths = result.screenshot_paths,
        system_prompt    = system_prompt,
        model            = model,
    )

    elapsed      = time.monotonic() - t_start
    report_final = _prepend_header(report_md, url, cap_label, elapsed)

    report_path = output_dir / "report.md"
    report_path.write_text(report_final, encoding="utf-8")

    # ── PDF generation ──────────────────────────────────────────────────────
    if pdf:
        print("[leafscan] Generating PDF ...", flush=True)
        pdf_path = md_to_pdf(
            report_final,
            output_dir / "report.pdf",
            screenshot_paths=result.screenshot_paths,
        )
        print(f"[leafscan] PDF saved -> {pdf_path}", flush=True)

    print(f"\n[leafscan] Done in {elapsed:.1f}s -> {report_path}", flush=True)
    return report_path


# ── Helpers ────────────────────────────────────────────────────────────────────

def _make_output_dir(url: str) -> Path:
    domain    = urlparse(url).hostname or "unknown"
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    out       = _OUTPUTS_DIR / f"{domain}_{timestamp}"
    out.mkdir(parents=True, exist_ok=True)
    return out


def _write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def _prepend_header(report_md: str, url: str, cap_label: str, elapsed: float) -> str:
    now    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    header = (
        f"<!-- generated by LeafScan | model: {cap_label} "
        f"| {now} | {elapsed:.1f}s -->\n\n"
    )
    return header + report_md
